set (CPACK_PACKAGE_NAME "PCLOUDS")
set (CPACK_PACKAGE_VERSION_MAJOR ${PCLOUDS_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${PCLOUDS_VERSION_MINOR})
set (CPACK_PACKAGE_VERSION_PATCH ${PCLOUDS_VERSION_PATCH})
set (CPACK_PACKAGE_VENDOR ${PCLOUDS_VENDOR})
set (CPACK_PACKAGE_CONTACT ${PCLOUDS_AUTHOR_EMAIL})
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PCLOUDS_DESCRIPTION})
#set (CPACK_PACKAGE_DESCRIPTION_FILE ${PCLOUDS_SOURCE_DIR}/README.md)

set (CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set (CPACK_DEBIAN_PACKAGE_DEPENDS "cmake (>=2.8), gcc (>=4:4.8), g++ (>=4:4.8)")

include (CPack)
